browser=chrome
url=https://www.saucedemo.com/
username=standard_user
password=secret_sauce
implicitWaitSeconds=10
explicitWaitSeconds=20
remote=false
gridUrl=http://localhost:4444/wd/hub
headless=false
